### ISSUE TITLE
posgres support? 

### ISSUE THREAD

**Issue by sokoow** [1backend/1backend#157]
do you plan any postgres support?

**Comment by crufter** [comment]
@sokoow 

Hi there!

We are not working on 1backend at the moment due to it requiring a pretty big engineering effort and since then we all got jobs that keep us pretty busy.

It's still our love-child and thinking about how could we resurrect it, especially after using other platforms provided by the bigcorps and them being very annoying to use!

But for the time being it's just being left as it is. If you feel like hacking on it you will get our support, and we will give you privileges to do so.

Cheers

**Comment by sokoow** [comment]
fiar point and thanks for pumping out such a nice project :)
